apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: karma-dev  # Asegúrate de que esté en el mismo namespace donde se va a usar
spec:
  acme:
    # Los parámetros ACME específicos
    server: https://acme-v02.api.letsencrypt.org/directory
    email: christian.garcia-martin@viseo.com
    privateKeySecretRef:
      name: letsencrypt-prod-key  # El secret donde se guardará la clave privada
    solvers:
    - http01:
        ingress: {}  # Solucionador HTTP-01
